name: flutter_reaction_button
description: Flutter button reaction it is fully customizable widget such as Facebook reaction button
homepage: https://github.com/GeekAbdelouahed/flutter-reaction-button
repository: https://github.com/GeekAbdelouahed/flutter-reaction-button.git
version: 2.0.1+3

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter: