name: flutter_reaction_button
description: Flutter Reaction Button is a customizable Flutter package that allows you to easily create interactive buttons with reaction emojis, similar to Facebook's iconic reaction buttons.
homepage: https://github.com/GeekAbdelouahed/flutter-reaction-button
repository: https://github.com/GeekAbdelouahed/flutter-reaction-button.git
version: 3.0.0+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
