name: Publishing pipeline

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    permissions:
      id-token: write
    uses: subosito/flutter-action@v2
    with:
      environment: pub.dev